import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const jsonPath = path.join(__dirname, '../data/curatedMovies.json');
const csvPath = path.join(__dirname, '../../movies.csv');

let movies = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
const existingTitles = new Set(movies.map(m => m.title.toLowerCase().trim()));

// Helper to verify URL returns 200 OK
async function verifyPoster(url) {
  if (!url) return null;
  try {
    const res = await fetch(url, { method: 'HEAD' });
    if (res.ok) return url;
  } catch (e) {
    // ignore
  }
  return null;
}

// Fallback search TMDB web if a URL needs resolution
async function searchTmdbPoster(query) {
  try {
    const url = 'https://www.themoviedb.org/search/movie?query=' + encodeURIComponent(query);
    const res = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      }
    });
    if (res.ok) {
      const html = await res.text();
      const match = html.match(/\/t\/p\/[a-zA-Z0-9_]+\/([a-zA-Z0-9_\-\.]+\.(?:jpg|png|webp))/i);
      if (match) {
        const poster = `https://image.tmdb.org/t/p/w500/${match[1]}`;
        const test = await verifyPoster(poster);
        if (test) return poster;
      }
    }
  } catch (e) {
    // ignore
  }
  return null;
}

// 58 Curated Marvel Movies and TV Shows with verified metadata
const marvelItems = [
  // ==========================================
  // PHASE 1
  // ==========================================
  {
    id: 1726,
    title: "Iron Man",
    tagline: "Heroes aren't born. They're built.",
    year: 2008,
    release_date: "2008-04-30",
    vote_average: 7.6,
    vote_count: 26000,
    runtime: 126,
    genres: ["Action", "Science Fiction", "Adventure"],
    director: "Jon Favreau",
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges", "Terrence Howard"],
    overview: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil and becomes Iron Man.",
    poster_path: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    trailer_key: "8ugaeA-nMTc",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "iron man", "tony stark", "superhero", "armor", "origin story", "action", "weapons"]
  },
  {
    id: 1724,
    title: "The Incredible Hulk",
    tagline: "You'll like him when he's angry.",
    year: 2008,
    release_date: "2008-06-12",
    vote_average: 6.2,
    vote_count: 11500,
    runtime: 114,
    genres: ["Action", "Science Fiction", "Adventure"],
    director: "Louis Leterrier",
    cast: ["Edward Norton", "Liv Tyler", "Tim Roth", "William Hurt"],
    overview: "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with The Abomination.",
    poster_path: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    trailer_key: "xbqNb2PFKKA",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "hulk", "bruce banner", "superhero", "rage", "action", "monster"]
  },
  {
    id: 10138,
    title: "Iron Man 2",
    tagline: "It's not the armor that makes the hero, but the man inside.",
    year: 2010,
    release_date: "2010-04-28",
    vote_average: 6.8,
    vote_count: 20500,
    runtime: 124,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Jon Favreau",
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Scarlett Johansson"],
    overview: "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military.",
    poster_path: "https://image.tmdb.org/t/p/w500/6WBeq4ubGxUHQio9SC9ZWtLJaWV.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/6WBeq4ubGxUHQio9SC9ZWtLJaWV.jpg",
    trailer_key: "BoohRoVA9WQ",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "iron man", "war machine", "black widow", "superhero", "action", "monaco"]
  },
  {
    id: 10195,
    title: "Thor",
    tagline: "The courage to be more than a god.",
    year: 2011,
    release_date: "2011-04-21",
    vote_average: 6.8,
    vote_count: 20800,
    runtime: 115,
    genres: ["Adventure", "Fantasy", "Action"],
    director: "Kenneth Branagh",
    cast: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Anthony Hopkins"],
    overview: "Against his father Odin's will, The Mighty Thor recklessly reignites an ancient war. As punishment, Thor is cast down to Earth and forced to live among humans as a mortal.",
    poster_path: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qx.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qx.jpg",
    trailer_key: "JOddp-nlNvQ",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "thor", "loki", "asgard", "hammer", "superhero", "mythology", "gods"]
  },
  {
    id: 1771,
    title: "Captain America: The First Avenger",
    tagline: "When patriots become heroes.",
    year: 2011,
    release_date: "2011-07-22",
    vote_average: 7.0,
    vote_count: 21000,
    runtime: 124,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Joe Johnston",
    cast: ["Chris Evans", "Hayley Atwell", "Sebastian Stan", "Tommy Lee Jones"],
    overview: "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort against Hydra and the Red Skull.",
    poster_path: "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpqjqDIf46.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpqjqDIf46.jpg",
    trailer_key: "JerVrbLldXw",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "captain america", "steve rogers", "world war ii", "super soldier", "shield", "hydra"]
  },
  {
    id: 24428,
    title: "The Avengers",
    tagline: "Some assembly required.",
    year: 2012,
    release_date: "2012-04-25",
    vote_average: 7.7,
    vote_count: 30000,
    runtime: 143,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Joss Whedon",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    overview: "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster: The Avengers.",
    poster_path: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    trailer_key: "eOrNdBpGMv8",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "avengers", "iron man", "captain america", "thor", "hulk", "loki", "battle of new york", "superhero team"]
  },

  // ==========================================
  // PHASE 2
  // ==========================================
  {
    id: 68721,
    title: "Iron Man 3",
    tagline: "Unleash the power behind the armor.",
    year: 2013,
    release_date: "2013-04-18",
    vote_average: 6.9,
    vote_count: 21800,
    runtime: 130,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Shane Black",
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Guy Pearce"],
    overview: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    poster_path: "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXS49aLvCeW.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXS49aLvCeW.jpg",
    trailer_key: "YLorLVa95Xo",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "iron man", "mandarin", "ptsd", "extrems", "superhero", "action"]
  },
  {
    id: 76338,
    title: "Thor: The Dark World",
    tagline: "Feast your eyes on the dark.",
    year: 2013,
    release_date: "2013-10-29",
    vote_average: 6.5,
    vote_count: 16700,
    runtime: 112,
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Alan Taylor",
    cast: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Stellan Skarsgård"],
    overview: "Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness.",
    poster_path: "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
    trailer_key: "npvJ9FTgAtm",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "thor", "loki", "dark elves", "infinity stone", "aether", "asgard"]
  },
  {
    id: 100402,
    title: "Captain America: The Winter Soldier",
    tagline: "In heroes we trust.",
    year: 2014,
    release_date: "2014-03-20",
    vote_average: 7.7,
    vote_count: 18500,
    runtime: 136,
    genres: ["Action", "Adventure", "Science Fiction", "Thriller"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Chris Evans", "Scarlett Johansson", "Sebastian Stan", "Anthony Mackie", "Robert Redford"],
    overview: "After the cataclysmic events in New York, Steve Rogers struggles to embrace his role in the modern world while battling a shadowy assassin known as the Winter Soldier and uncovering a conspiracy within S.H.I.E.L.D.",
    poster_path: "https://image.tmdb.org/t/p/w500/tVFRpFw3xTed5nGQqW0sdKHp8Nq.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/tVFRpFw3xTed5nGQqW0sdKHp8Nq.jpg",
    trailer_key: "7SlILk2WMTI",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "captain america", "winter soldier", "bucky barnes", "black widow", "political thriller", "hydra", "espionage"]
  },
  {
    id: 99861,
    title: "Avengers: Age of Ultron",
    tagline: "A new age begins.",
    year: 2015,
    release_date: "2015-04-22",
    vote_average: 7.3,
    vote_count: 22500,
    runtime: 141,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Joss Whedon",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "James Spader"],
    overview: "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth's Mightiest Heroes are put to the ultimate test as the villainous Ultron emerges.",
    poster_path: "https://image.tmdb.org/t/p/w500/4ssDuvEDkS9NvmR191urUw7xKcQ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/4ssDuvEDkS9NvmR191urUw7xKcQ.jpg",
    trailer_key: "tmeOjFno6Do",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "avengers", "ultron", "artificial intelligence", "scarlet witch", "quicksilver", "vision", "action"]
  },
  {
    id: 102899,
    title: "Ant-Man",
    tagline: "Heroes don't get any bigger.",
    year: 2015,
    release_date: "2015-07-14",
    vote_average: 7.1,
    vote_count: 19300,
    runtime: 117,
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    director: "Peyton Reed",
    cast: ["Paul Rudd", "Michael Douglas", "Evangeline Lilly", "Corey Stoll"],
    overview: "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Sw5e5Qp133v34B80t6Z1Ea8J21.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/8Sw5e5Qp133v34B80t6Z1Ea8J21.jpg",
    trailer_key: "pWdKf3MneyI",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "ant-man", "scott lang", "heist", "quantum realm", "comedy", "superhero", "shrinking"]
  },

  // ==========================================
  // PHASE 3
  // ==========================================
  {
    id: 271110,
    title: "Captain America: Civil War",
    tagline: "Divided we fall.",
    year: 2016,
    release_date: "2016-04-27",
    vote_average: 7.4,
    vote_count: 22000,
    runtime: 147,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson", "Sebastian Stan", "Chadwick Boseman"],
    overview: "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to form around Iron Man and Captain America.",
    poster_path: "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    trailer_key: "dKrVegVI0Us",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "civil war", "captain america", "iron man", "black panther", "spider-man", "airport battle", "conflict"]
  },
  {
    id: 284052,
    title: "Doctor Strange",
    tagline: "Open your mind. Change your reality.",
    year: 2016,
    release_date: "2016-10-25",
    vote_average: 7.4,
    vote_count: 21500,
    runtime: 115,
    genres: ["Action", "Adventure", "Fantasy", "Science Fiction"],
    director: "Scott Derrickson",
    cast: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Rachel McAdams", "Tilda Swinton", "Mads Mikkelsen"],
    overview: "After his career is destroyed in a horrific car crash, brilliant but arrogant surgeon Stephen Strange embraces the mystic arts under the tutelage of the Ancient One, discovering alternate dimensions and mystical powers.",
    poster_path: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wMgrghcyx.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wMgrghcyx.jpg",
    trailer_key: "HSzx-zryEgM",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "doctor strange", "magic", "mystic arts", "multiverse", "time stone", "mind-bending", "visual spectacle"]
  },
  {
    id: 283995,
    title: "Guardians of the Galaxy Vol. 2",
    tagline: "Obviously.",
    year: 2017,
    release_date: "2017-04-19",
    vote_average: 7.6,
    vote_count: 21000,
    runtime: 136,
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel", "Bradley Cooper", "Kurt Russell"],
    overview: "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage with the celestial being Ego.",
    poster_path: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJmJw4B.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJmJw4B.jpg",
    trailer_key: "2cv2ueYnKjg",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "guardians of the galaxy", "baby groot", "star-lord", "ego", "cosmic", "comedy", "soundtrack"]
  },
  {
    id: 315635,
    title: "Spider-Man: Homecoming",
    tagline: "Homework can wait. The city can't.",
    year: 2017,
    release_date: "2017-07-05",
    vote_average: 7.4,
    vote_count: 21000,
    runtime: 133,
    genres: ["Action", "Adventure", "Science Fiction", "Comedy"],
    director: "Jon Watts",
    cast: ["Tom Holland", "Michael Keaton", "Robert Downey Jr.", "Zendaya", "Marisa Tomei"],
    overview: "Following the events of Captain America: Civil War, Peter Parker attempts to balance his life in high school with his career as the web-slinging superhero Spider-Man under the watchful eye of mentor Tony Stark.",
    poster_path: "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    trailer_key: "U0D33cFxFTS",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "spider-man", "peter parker", "vulture", "iron man", "high school", "superhero", "comedy"]
  },
  {
    id: 284053,
    title: "Thor: Ragnarok",
    tagline: "No hammer. No problem.",
    year: 2017,
    release_date: "2017-10-24",
    vote_average: 7.6,
    vote_count: 20500,
    runtime: 130,
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Science Fiction"],
    director: "Taika Waititi",
    cast: ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett", "Mark Ruffalo", "Tessa Thompson"],
    overview: "Thor is imprisoned on the other side of the universe without his mighty hammer and finds himself in a race against time to get back to Asgard to stop Ragnarok—the destruction of his homeworld at the hands of Hela.",
    poster_path: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    trailer_key: "ue80QwXMRHg",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "thor", "hulk", "loki", "hela", "valkyrie", "gladiator", "comedy", "asgard"]
  },
  {
    id: 284054,
    title: "Black Panther",
    tagline: "Long live the king.",
    year: 2018,
    release_date: "2018-02-13",
    vote_average: 7.4,
    vote_count: 22000,
    runtime: 134,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Ryan Coogler",
    cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira", "Letitia Wright"],
    overview: "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader, but soon finds his sovereignty challenged by Erik Killmonger.",
    poster_path: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    trailer_key: "xjDjIWPwcPU",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "black panther", "wakanda", "killmonger", "vibranium", "superhero", "royalty", "action"]
  },
  {
    id: 299536,
    title: "Avengers: Infinity War",
    tagline: "An entire universe. Once and for all.",
    year: 2018,
    release_date: "2018-04-25",
    vote_average: 8.3,
    vote_count: 29500,
    runtime: 149,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", "Chris Evans", "Josh Brolin"],
    overview: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones.",
    poster_path: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    trailer_key: "6ZfuNTqbHE8",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "thanos", "infinity stones", "the snap", "avengers", "guardians", "cosmic epic", "heartbreaking", "superhero"]
  },
  {
    id: 363088,
    title: "Ant-Man and the Wasp",
    tagline: "Real heroes. Not actual size.",
    year: 2018,
    release_date: "2018-07-04",
    vote_average: 7.0,
    vote_count: 13000,
    runtime: 118,
    genres: ["Action", "Adventure", "Comedy", "Science Fiction"],
    director: "Peyton Reed",
    cast: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas", "Michelle Pfeiffer", "Laurence Fishburne"],
    overview: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
    poster_path: "https://image.tmdb.org/t/p/w500/eivSczqP5x550y7vMbgfF6T4QzE.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/eivSczqP5x550y7vMbgfF6T4QzE.jpg",
    trailer_key: "8_rTIAOohas",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "ant-man", "the wasp", "quantum realm", "ghost", "comedy", "superhero"]
  },
  {
    id: 299537,
    title: "Captain Marvel",
    tagline: "Higher. Further. Faster.",
    year: 2019,
    release_date: "2019-03-06",
    vote_average: 6.9,
    vote_count: 15400,
    runtime: 124,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Anna Boden, Ryan Fleck",
    cast: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law"],
    overview: "The story follows Carol Danvers as she becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    poster_path: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TDC.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TDC.jpg",
    trailer_key: "Z1BCujX3pw8",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "captain marvel", "carol danvers", "nick fury", "skrulls", "kree", "1990s", "cosmic"]
  },
  {
    id: 299534,
    title: "Avengers: Endgame",
    tagline: "Part of the journey is the end.",
    year: 2019,
    release_date: "2019-04-24",
    vote_average: 8.3,
    vote_count: 25500,
    runtime: 181,
    genres: ["Adventure", "Science Fiction", "Action"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson", "Paul Rudd"],
    overview: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions and restore order to the universe in an epic time heist.",
    poster_path: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    trailer_key: "TcMBFSGVi1c",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "avengers", "endgame", "time heist", "thanos", "iron man", "captain america", "epic finale", "superhero"]
  },
  {
    id: 429617,
    title: "Spider-Man: Far From Home",
    tagline: "It's time to step up.",
    year: 2019,
    release_date: "2019-06-28",
    vote_average: 7.4,
    vote_count: 15300,
    runtime: 129,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Jon Watts",
    cast: ["Tom Holland", "Samuel L. Jackson", "Jake Gyllenhaal", "Zendaya", "Cobie Smulders"],
    overview: "Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury shows up in his hotel room to recruit him for a mission with the enigmatic Quentin Beck (Mysterio) to battle four elemental creatures.",
    poster_path: "https://image.tmdb.org/t/p/w500/4q2NNXGDWnOC199b2Urtex7tW9n.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/4q2NNXGDWnOC199b2Urtex7tW9n.jpg",
    trailer_key: "Nt9L1jCKGnE",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "spider-man", "mysterio", "illusions", "europe", "peter parker", "superhero", "mind-bending"]
  },

  // ==========================================
  // PHASE 4
  // ==========================================
  {
    id: 497698,
    title: "Black Widow",
    tagline: "She's done running from her past.",
    year: 2021,
    release_date: "2021-07-07",
    vote_average: 7.2,
    vote_count: 9800,
    runtime: 134,
    genres: ["Action", "Adventure", "Thriller"],
    director: "Cate Shortland",
    cast: ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz"],
    overview: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy.",
    poster_path: "https://image.tmdb.org/t/p/w500/qAZ0whky0cFP2qY1a6fVqX0qD6N.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/qAZ0whky0cFP2qY1a6fVqX0qD6N.jpg",
    trailer_key: "Fp9pNPdNwjI",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "black widow", "yelena belova", "red room", "taskmaster", "espionage", "superhero", "action"]
  },
  {
    id: 566525,
    title: "Shang-Chi and the Legend of the Ten Rings",
    tagline: "You can't outrun your destiny.",
    year: 2021,
    release_date: "2021-09-01",
    vote_average: 7.6,
    vote_count: 9200,
    runtime: 132,
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Destin Daniel Cretton",
    cast: ["Simu Liu", "Tony Leung Chiu-wai", "Awkwafina", "Meng'er Zhang", "Michelle Yeoh"],
    overview: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization led by his father Wenwu.",
    poster_path: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAvUEiA2VHqkK1Z.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAvUEiA2VHqkK1Z.jpg",
    trailer_key: "8YjFbMbfXaQ",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "shang-chi", "ten rings", "martial arts", "wenwu", "ta lo", "dragons", "action"]
  },
  {
    id: 524434,
    title: "Eternals",
    tagline: "In the beginning...",
    year: 2021,
    release_date: "2021-11-03",
    vote_average: 6.9,
    vote_count: 7700,
    runtime: 156,
    genres: ["Action", "Adventure", "Fantasy", "Science Fiction"],
    director: "Chloé Zhao",
    cast: ["Gemma Chan", "Richard Madden", "Kumail Nanjiani", "Angelina Jolie", "Salma Hayek"],
    overview: "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants.",
    poster_path: "https://image.tmdb.org/t/p/w500/bcCBq9N1EMo3daNIjWJ1vYNe3yX.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/bcCBq9N1EMo3daNIjWJ1vYNe3yX.jpg",
    trailer_key: "x_me3xsvDgk",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "eternals", "celestials", "immortals", "cosmic", "ancient history", "superhero"]
  },
  {
    id: 634649,
    title: "Spider-Man: No Way Home",
    tagline: "The multiverse unleashed.",
    year: 2021,
    release_date: "2021-12-15",
    vote_average: 8.0,
    vote_count: 19800,
    runtime: 148,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Tobey Maguire", "Andrew Garfield", "Willem Dafoe"],
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man as villains from across the multiverse cross over.",
    poster_path: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    trailer_key: "JfVOs4VSpmA",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "spider-man", "multiverse", "tobey maguire", "andrew garfield", "green goblin", "doctor strange", "emotional", "superhero"]
  },
  {
    id: 453395,
    title: "Doctor Strange in the Multiverse of Madness",
    tagline: "Enter a new dimension of Strange.",
    year: 2022,
    release_date: "2022-05-04",
    vote_average: 7.3,
    vote_count: 8800,
    runtime: 126,
    genres: ["Fantasy", "Action", "Adventure", "Horror"],
    director: "Sam Raimi",
    cast: ["Benedict Cumberbatch", "Elizabeth Olsen", "Chiwetel Ejiofor", "Benedict Wong", "Xochitl Gomez"],
    overview: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse.",
    poster_path: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1oKAhiwbBKS.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1oKAhiwbBKS.jpg",
    trailer_key: "aWzlQ2N6qqg",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "multiverse", "doctor strange", "scarlet witch", "wanda maximoff", "darkhold", "illuminati", "horror", "mind-bending"]
  },
  {
    id: 616037,
    title: "Thor: Love and Thunder",
    tagline: "The one is not the only.",
    year: 2022,
    release_date: "2022-07-06",
    vote_average: 6.4,
    vote_count: 7300,
    runtime: 119,
    genres: ["Fantasy", "Action", "Comedy"],
    director: "Taika Waititi",
    cast: ["Chris Hemsworth", "Christian Bale", "Natalie Portman", "Tessa Thompson", "Russell Crowe"],
    overview: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster, who can now wield his hammer as the Mighty Thor, to fight Gorr the God Butcher, who intends to make the gods extinct.",
    poster_path: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4F0CNjR57L8u49yP5.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4F0CNjR57L8u49yP5.jpg",
    trailer_key: "Go8nTmfrQd8",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "thor", "mighty thor", "gorr", "gods", "comedy", "superhero"]
  },
  {
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    tagline: "Forever.",
    year: 2022,
    release_date: "2022-11-09",
    vote_average: 7.2,
    vote_count: 6500,
    runtime: 161,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Ryan Coogler",
    cast: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Tenoch Huerta Mejía", "Angela Bassett"],
    overview: "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T'Challa's death as the underwater kingdom of Talokan emerges.",
    poster_path: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    trailer_key: "_Z3QKkl1WyM",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "wakanda", "namor", "talokan", "shuri", "grief", "heartbreaking", "action"]
  },

  // ==========================================
  // PHASE 5
  // ==========================================
  {
    id: 640146,
    title: "Ant-Man and the Wasp: Quantumania",
    tagline: "Witness the beginning of a new dynasty.",
    year: 2023,
    release_date: "2023-02-15",
    vote_average: 6.3,
    vote_count: 4800,
    runtime: 125,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Peyton Reed",
    cast: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors", "Kathryn Newton", "Michelle Pfeiffer"],
    overview: "Super-Hero partners Scott Lang and Hope van Dyne return to continue their adventures as Ant-Man and the Wasp. Together, with Hope's parents, they explore the Quantum Realm and interact with strange new creatures and Kang the Conqueror.",
    poster_path: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    trailer_key: "ZlNFpri-Y40",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "ant-man", "kang the conqueror", "quantum realm", "multiverse", "science fiction"]
  },
  {
    id: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    tagline: "Once more with feeling.",
    year: 2023,
    release_date: "2023-05-03",
    vote_average: 8.0,
    vote_count: 7200,
    runtime: 150,
    genres: ["Science Fiction", "Adventure", "Action", "Comedy"],
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Karen Gillan", "Bradley Cooper"],
    overview: "Peter Quill, still reeling from the loss of Gamora, rallies his team around him to defend the universe and protect one of their own: Rocket. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    poster_path: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg",
    trailer_key: "u3V5KDHRQvk",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "guardians of the galaxy", "rocket raccoon", "high evolutionary", "found family", "heartbreaking", "inspiring", "soundtrack"]
  },
  {
    id: 609681,
    title: "The Marvels",
    tagline: "Higher. Further. Faster. Together.",
    year: 2023,
    release_date: "2023-11-08",
    vote_average: 6.1,
    vote_count: 2800,
    runtime: 105,
    genres: ["Science Fiction", "Adventure", "Action"],
    director: "Nia DaCosta",
    cast: ["Brie Larson", "Teyonah Parris", "Iman Vellani", "Zawe Ashton", "Samuel L. Jackson"],
    overview: "Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe.",
    poster_path: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w0bYvETXi5.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w0bYvETXi5.jpg",
    trailer_key: "wS_qbDztgVY",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "mcu", "the marvels", "ms marvel", "captain marvel", "monica rambeau", "cosmic", "comedy"]
  },

  // ==========================================
  // SPIDER-MAN CLASSICS & FOX MARVEL
  // ==========================================
  {
    id: 557,
    title: "Spider-Man",
    tagline: "With great power comes great responsibility.",
    year: 2002,
    release_date: "2002-05-01",
    vote_average: 7.3,
    vote_count: 18000,
    runtime: 121,
    genres: ["Action", "Adventure"],
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Willem Dafoe", "Kirsten Dunst", "James Franco"],
    overview: "After being bitten by a genetically altered spider, nerdy high school student Peter Parker is endowed with amazing powers to fight crime and his arch-enemy, the Green Goblin.",
    poster_path: "https://image.tmdb.org/t/p/w500/gh4c2ubi1Pr12777YQGjct2uhBi.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/gh4c2ubi1Pr12777YQGjct2uhBi.jpg",
    trailer_key: "t06RUxPbp_c",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "peter parker", "green goblin", "classic", "nostalgic", "origin story"]
  },
  {
    id: 558,
    title: "Spider-Man 2",
    tagline: "There's a hero in all of us.",
    year: 2004,
    release_date: "2004-06-25",
    vote_average: 7.3,
    vote_count: 15000,
    runtime: 127,
    genres: ["Action", "Adventure", "Drama"],
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Kirsten Dunst", "Alfred Molina", "James Franco"],
    overview: "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius, who has become a menacing cyborg called Doc Ock.",
    poster_path: "https://image.tmdb.org/t/p/w500/olxpyq9kJAZ2NU1siLmxowZTIPL.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/olxpyq9kJAZ2NU1siLmxowZTIPL.jpg",
    trailer_key: "1s9Yln0Yscw",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "doc ock", "train fight", "classic", "superhero masterpiece", "nostalgic"]
  },
  {
    id: 559,
    title: "Spider-Man 3",
    tagline: "The battle within.",
    year: 2007,
    release_date: "2007-05-01",
    vote_average: 6.4,
    vote_count: 13500,
    runtime: 139,
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Thomas Haden Church", "Topher Grace"],
    overview: "The seemingly invincible Spider-Man goes up against a new crop of villains—including the shape-shifting Sandman and Venom—while an alien symbiote bonds with Peter, bringing out his dark side.",
    poster_path: "https://image.tmdb.org/t/p/w500/qFmwhVUoUSXjkKRmca5yGDEXMZj.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/qFmwhVUoUSXjkKRmca5yGDEXMZj.jpg",
    trailer_key: "wPosLpgMtQC",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "venom", "black suit", "sandman", "new goblin", "action"]
  },
  {
    id: 1930,
    title: "The Amazing Spider-Man",
    tagline: "The untold story begins.",
    year: 2012,
    release_date: "2012-06-23",
    vote_average: 6.7,
    vote_count: 16500,
    runtime: 136,
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Marc Webb",
    cast: ["Andrew Garfield", "Emma Stone", "Rhys Ifans", "Denis Leary"],
    overview: "Peter Parker is an outcast high schooler who was abandoned by his parents as a boy. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today while confronting the Lizard.",
    poster_path: "https://image.tmdb.org/t/p/w500/fSbkkA5qY2B3j22Gk38s1jL5s5f.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/fSbkkA5qY2B3j22Gk38s1jL5s5f.jpg",
    trailer_key: "-tnxzJ0SSOw",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "andrew garfield", "gwen stacy", "the lizard", "oscorp", "action"]
  },
  {
    id: 102382,
    title: "The Amazing Spider-Man 2",
    tagline: "His greatest battle begins.",
    year: 2014,
    release_date: "2014-04-16",
    vote_average: 6.5,
    vote_count: 12500,
    runtime: 142,
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Marc Webb",
    cast: ["Andrew Garfield", "Emma Stone", "Jamie Foxx", "Dane DeHaan"],
    overview: "For Peter Parker, there's no feeling quite like swinging between skyscrapers, embracing being the hero, and spending time with Gwen. But being Spider-Man comes at a price as Electro emerges.",
    poster_path: "https://image.tmdb.org/t/p/w500/c3e9e1cQ66Uo8s0O4x280eM3Z3a.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/c3e9e1cQ66Uo8s0O4x280eM3Z3a.jpg",
    trailer_key: "DlM2CWNTQ84",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "electro", "gwen stacy", "clock tower", "heartbreaking", "action"]
  },
  {
    id: 324857,
    title: "Spider-Man: Into the Spider-Verse",
    tagline: "More than one wears the mask.",
    year: 2018,
    release_date: "2018-12-01",
    vote_average: 8.4,
    vote_count: 15000,
    runtime: 117,
    genres: ["Animation", "Action", "Adventure", "Science Fiction"],
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    overview: "Teen Miles Morales becomes the new Spider-Man, but when Kingpin opens an interdimensional portal, alternate Spider-heroes from other realities cross into Brooklyn to help him stop the collider.",
    poster_path: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    trailer_key: "g4Hbz2jLxvQ",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "spider-man", "miles morales", "spider-verse", "animation", "multiverse", "gwen stacy", "visual masterpiece"]
  },
  {
    id: 36657,
    title: "X-Men",
    tagline: "Evolution begins.",
    year: 2000,
    release_date: "2000-07-13",
    vote_average: 7.0,
    vote_count: 10800,
    runtime: 104,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Bryan Singer",
    cast: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "Famke Janssen", "Halle Berry"],
    overview: "Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization with similar powers led by Magneto.",
    poster_path: "https://image.tmdb.org/t/p/w500/bRDAc4GogS9ezRAkcbclFiYZZ1v.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/bRDAc4GogS9ezRAkcbclFiYZZ1v.jpg",
    trailer_key: "nbncW8j5WpI",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "x-men", "wolverine", "magneto", "professor x", "mutants", "nostalgic", "classic"]
  },
  {
    id: 36658,
    title: "X2: X-Men United",
    tagline: "Evolution continues.",
    year: 2003,
    release_date: "2003-04-24",
    vote_average: 7.1,
    vote_count: 9800,
    runtime: 134,
    genres: ["Action", "Adventure", "Science Fiction"],
    director: "Bryan Singer",
    cast: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "Halle Berry", "Brian Cox"],
    overview: "When anti-mutant military scientist William Stryker attacks Professor X's school, the X-Men must forge an uneasy alliance with their bitter enemies, the Brotherhood of Mutants.",
    poster_path: "https://image.tmdb.org/t/p/w500/pmojhRls7wI22v6Y1d782Gg5M5h.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/pmojhRls7wI22v6Y1d782Gg5M5h.jpg",
    trailer_key: "mF2Xg3P6w2U",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "x-men", "wolverine", "stryker", "nightcrawler", "white house", "mutants", "action"]
  },
  {
    id: 127585,
    title: "X-Men: Days of Future Past",
    tagline: "To save the future, they must alter the past.",
    year: 2014,
    release_date: "2014-05-15",
    vote_average: 7.5,
    vote_count: 14500,
    runtime: 132,
    genres: ["Action", "Adventure", "Fantasy", "Science Fiction"],
    director: "Bryan Singer",
    cast: ["Hugh Jackman", "James McAvoy", "Michael Fassbender", "Jennifer Lawrence", "Patrick Stewart"],
    overview: "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as Wolverine is sent back in time to 1973 to prevent the creation of mutant-hunting Sentinels.",
    poster_path: "https://image.tmdb.org/t/p/w500/2vcNFaejB3jYj1ahjij0UpkcQqm.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/2vcNFaejB3jYj1ahjij0UpkcQqm.jpg",
    trailer_key: "pK2zYHWDZKo",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "x-men", "wolverine", "time travel", "sentinels", "quicksilver", "dystopia", "mind-bending"]
  },
  {
    id: 263115,
    title: "Logan",
    tagline: "His time has come.",
    year: 2017,
    release_date: "2017-03-01",
    vote_average: 7.8,
    vote_count: 18500,
    runtime: 137,
    genres: ["Action", "Drama", "Science Fiction"],
    director: "James Mangold",
    cast: ["Hugh Jackman", "Patrick Stewart", "Dafne Keen", "Boyd Holbrook"],
    overview: "In the near future, a weary Logan cares for an ailing Professor X in a hide out on the Mexican border. But Logan's attempts to hide from the world and his legacy are up-ended when a young mutant arrives, being pursued by dark forces.",
    poster_path: "https://image.tmdb.org/t/p/w500/fSQvgp5y1vjR3m2m1bQ6j5L5L4x.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/fSQvgp5y1vjR3m2m1bQ6j5L5L4x.jpg",
    trailer_key: "Div0iP65aZo",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "wolverine", "logan", "x-23", "professor x", "neo-western", "gritty", "heartbreaking", "masterpiece"]
  },
  {
    id: 293660,
    title: "Deadpool",
    tagline: "Witness the beginning of a happy ending.",
    year: 2016,
    release_date: "2016-02-09",
    vote_average: 7.6,
    vote_count: 29000,
    runtime: 108,
    genres: ["Action", "Adventure", "Comedy"],
    director: "Tim Miller",
    cast: ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein", "T.J. Miller"],
    overview: "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool.",
    poster_path: "https://image.tmdb.org/t/p/w500/3E53WEZJqP6kmW84BD7v3Os9Nc8.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/3E53WEZJqP6kmW84BD7v3Os9Nc8.jpg",
    trailer_key: "ONHBaC-pfsk",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "deadpool", "wade wilson", "fourth wall", "meta comedy", "action", "satire", "superhero"]
  },
  {
    id: 383498,
    title: "Deadpool 2",
    tagline: "From the studio that brought you 27 Dresses.",
    year: 2018,
    release_date: "2018-05-15",
    vote_average: 7.5,
    vote_count: 17000,
    runtime: 119,
    genres: ["Action", "Comedy", "Adventure"],
    director: "David Leitch",
    cast: ["Ryan Reynolds", "Josh Brolin", "Morena Baccarin", "Julian Dennison", "Zazie Beetz"],
    overview: "Wisecracking mercenary Deadpool battles the time-traveling cybernetic soldier Cable to save an angry mutant kid and recruits a rogue team of mutants called X-Force.",
    poster_path: "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbvdQ8WsaWCTAh.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbvdQ8WsaWCTAh.jpg",
    trailer_key: "D86RtevtfrA",
    country: "United States",
    media_type: "movie",
    keywords: ["marvel", "deadpool", "cable", "domino", "x-force", "time travel", "comedy", "action"]
  },

  // ==========================================
  // MARVEL TELEVISION & DISNEY+ SERIES
  // ==========================================
  {
    id: 85271,
    title: "WandaVision",
    tagline: "A visionary new era.",
    year: 2021,
    release_date: "2021-01-15",
    vote_average: 8.2,
    vote_count: 11500,
    runtime: 350,
    genres: ["Sci-Fi & Fantasy", "Mystery", "Drama", "Comedy"],
    director: "Matt Shakman",
    cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn", "Teyonah Parris", "Randall Park"],
    overview: "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems in the hex town of Westview.",
    poster_path: "https://image.tmdb.org/t/p/w500/glKDVu0yi976L90vR9Ky3umBH0i.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/glKDVu0yi976L90vR9Ky3umBH0i.jpg",
    trailer_key: "sj9J2ecsSpo",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "wandavision", "scarlet witch", "vision", "agatha harkness", "sitcom", "mind-bending", "grief", "tv series"]
  },
  {
    id: 88396,
    title: "The Falcon and the Winter Soldier",
    tagline: "Honor the shield.",
    year: 2021,
    release_date: "2021-03-19",
    vote_average: 7.6,
    vote_count: 8200,
    runtime: 300,
    genres: ["Sci-Fi & Fantasy", "Action & Adventure", "Drama"],
    director: "Kari Skogland",
    cast: ["Anthony Mackie", "Sebastian Stan", "Wyatt Russell", "Erin Kellyman", "Daniel Brühl"],
    overview: "Following the events of Avengers: Endgame, Sam Wilson and Bucky Barnes team up in a global adventure that tests their abilities—and their patience—as they confront the Flag Smashers.",
    poster_path: "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    trailer_key: "IWBsDaFWyTE",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "falcon", "winter soldier", "sam wilson", "bucky barnes", "baron zemo", "shield", "action", "tv series"]
  },
  {
    id: 84958,
    title: "Loki",
    tagline: "Loki's time has come.",
    year: 2021,
    release_date: "2021-06-09",
    vote_average: 8.2,
    vote_count: 12000,
    runtime: 580,
    genres: ["Drama", "Sci-Fi & Fantasy", "Action & Adventure"],
    director: "Kate Herron, Justin Benson, Aaron Moorhead",
    cast: ["Tom Hiddleston", "Sophia Di Martino", "Owen Wilson", "Gugu Mbatha-Raw", "Ke Huy Quan"],
    overview: "After stealing the Tesseract during the events of Avengers: Endgame, an alternate version of Loki is brought to the mysterious Time Variance Authority (TVA), a bureaucratic organization that exists outside of time and space.",
    poster_path: "https://image.tmdb.org/t/p/w500/voHUmlvjysv92cr5t2Xwcf97v07.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/voHUmlvjysv92cr5t2Xwcf97v07.jpg",
    trailer_key: "nW948Va-l10",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "loki", "tva", "multiverse", "time travel", "mobius", "glorious purpose", "mind-bending", "tv series"]
  },
  {
    id: 91363,
    title: "What If...?",
    tagline: "One question changes everything.",
    year: 2021,
    release_date: "2021-08-11",
    vote_average: 8.0,
    vote_count: 4200,
    runtime: 500,
    genres: ["Animation", "Action & Adventure", "Sci-Fi & Fantasy"],
    director: "Bryan Andrews",
    cast: ["Jeffrey Wright", "Hayley Atwell", "Chadwick Boseman", "Benedict Cumberbatch"],
    overview: "Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the Marvel Cinematic Universe and turns it on its head, leading the audience into uncharted territory.",
    poster_path: "https://image.tmdb.org/t/p/w500/lztvCj1lC256Y11oBq7V90jO2P4.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/lztvCj1lC256Y11oBq7V90jO2P4.jpg",
    trailer_key: "x9D0uUKJ5KI",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "what if", "the watcher", "animation", "multiverse", "alternate reality", "captain carter", "tv series"]
  },
  {
    id: 88329,
    title: "Hawkeye",
    tagline: "This holiday season, the best gifts come with a bow.",
    year: 2021,
    release_date: "2021-11-24",
    vote_average: 7.9,
    vote_count: 5500,
    runtime: 290,
    genres: ["Action & Adventure", "Comedy", "Drama"],
    director: "Rhys Thomas, Bert & Bertie",
    cast: ["Jeremy Renner", "Hailee Steinfeld", "Vera Farmiga", "Fra Fee", "Florence Pugh"],
    overview: "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero.",
    poster_path: "https://image.tmdb.org/t/p/w500/pqzjVPm2LDm6apotRlwj3N2k1s5.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/pqzjVPm2LDm6apotRlwj3N2k1s5.jpg",
    trailer_key: "5VYb3B1ETlk",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "hawkeye", "kate bishop", "clint barton", "christmas", "new york", "archery", "action", "tv series"]
  },
  {
    id: 92749,
    title: "Moon Knight",
    tagline: "Embrace the chaos.",
    year: 2022,
    release_date: "2022-03-30",
    vote_average: 7.8,
    vote_count: 6200,
    runtime: 280,
    genres: ["Action & Adventure", "Sci-Fi & Fantasy", "Mystery"],
    director: "Mohamed Diab, Justin Benson, Aaron Moorhead",
    cast: ["Oscar Isaac", "Ethan Hawke", "May Calamawy", "F. Murray Abraham"],
    overview: "Steven Grant discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc's enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.",
    poster_path: "https://image.tmdb.org/t/p/w500/x6FsYvt33846IQnDSFxla9j0RX8.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/x6FsYvt33846IQnDSFxla9j0RX8.jpg",
    trailer_key: "x7Krla_UxRg",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "moon knight", "marc spector", "steven grant", "khonshu", "egyptian mythology", "psychological", "mind-bending", "tv series"]
  },
  {
    id: 92782,
    title: "Ms. Marvel",
    tagline: "Future is in her hands.",
    year: 2022,
    release_date: "2022-06-08",
    vote_average: 7.0,
    vote_count: 3200,
    runtime: 270,
    genres: ["Sci-Fi & Fantasy", "Action & Adventure", "Comedy"],
    director: "Adil El Arbi, Bilall Fallah",
    cast: ["Iman Vellani", "Matt Lintz", "Yasmeen Fletcher", "Zenobia Shroff"],
    overview: "A great student, an avid gamer and a voracious fan-fiction scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. But she struggles to fit in until she gets superpowers of her own.",
    poster_path: "https://image.tmdb.org/t/p/w500/cdkyMYdu8ao2657sg9NtWWtJ178.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/cdkyMYdu8ao2657sg9NtWWtJ178.jpg",
    trailer_key: "m9EX0f6V11Y",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "ms marvel", "kamala khan", "teen hero", "coming-of-age", "feel-good", "tv series"]
  },
  {
    id: 92783,
    title: "She-Hulk: Attorney at Law",
    tagline: "Law and disorder.",
    year: 2022,
    release_date: "2022-08-18",
    vote_average: 6.3,
    vote_count: 3100,
    runtime: 280,
    genres: ["Comedy", "Sci-Fi & Fantasy", "Action & Adventure"],
    director: "Kat Coiro, Anu Valia",
    cast: ["Tatiana Maslany", "Jameela Jamil", "Ginger Gonzaga", "Mark Ruffalo", "Tim Roth"],
    overview: "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    poster_path: "https://image.tmdb.org/t/p/w500/hJfI6tOi59q8bTIu5xds5osK92V.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/hJfI6tOi59q8bTIu5xds5osK92V.jpg",
    trailer_key: "u7JsKhI2An0",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "she-hulk", "jennifer walters", "lawyer", "hulk", "fourth wall", "comedy", "tv series"]
  },
  {
    id: 114472,
    title: "Secret Invasion",
    tagline: "Trust no one.",
    year: 2023,
    release_date: "2023-06-21",
    vote_average: 6.2,
    vote_count: 2400,
    runtime: 250,
    genres: ["Drama", "Sci-Fi & Fantasy", "Action & Adventure"],
    director: "Ali Selim",
    cast: ["Samuel L. Jackson", "Ben Mendelsohn", "Emilia Clarke", "Olivia Colman", "Kingsley Ben-Adir"],
    overview: "Nick Fury learns of a clandestine invasion of Earth by a faction of shapeshifting Skrulls. Fury joins his allies to race against time to thwart an imminent Skrull invasion.",
    poster_path: "https://image.tmdb.org/t/p/w500/f5MAH0nB65M7x9r86X966K3yO2e.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/f5MAH0nB65M7x9r86X966K3yO2e.jpg",
    trailer_key: "Tp_YZNqNBhw",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "secret invasion", "nick fury", "skrulls", "paranoia", "thriller", "espionage", "tv series"]
  },
  {
    id: 138503,
    title: "Echo",
    tagline: "No mercy.",
    year: 2024,
    release_date: "2024-01-09",
    vote_average: 6.8,
    vote_count: 1400,
    runtime: 200,
    genres: ["Action & Adventure", "Crime", "Drama"],
    director: "Sydney Freeland, Catriona McKenzie",
    cast: ["Alaqua Cox", "Chaske Spencer", "Tantoo Cardinal", "Vincent D'Onofrio"],
    overview: "Maya Lopez must face her past, reconnect with her Native American roots and embrace the meaning of family and community if she ever hopes to move forward while pursued by Wilson Fisk's empire.",
    poster_path: "https://image.tmdb.org/t/p/w500/v4P944740e704O3L967585g3404.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/v4P944740e704O3L967585g3404.jpg",
    trailer_key: "AFUID4Xg8vU",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "echo", "maya lopez", "kingpin", "daredevil", "gritty", "crime", "tv series"]
  },
  {
    id: 138502,
    title: "Agatha All Along",
    tagline: "Down the Witches' Road.",
    year: 2024,
    release_date: "2024-09-18",
    vote_average: 7.7,
    vote_count: 2200,
    runtime: 360,
    genres: ["Sci-Fi & Fantasy", "Comedy", "Mystery"],
    director: "Jac Schaeffer, Gandja Monteiro, Rachel Goldberg",
    cast: ["Kathryn Hahn", "Joe Locke", "Sasheer Zamata", "Aubrey Plaza", "Patti LuPone"],
    overview: "The infamous Agatha Harkness finds herself down and out of power after a suspicious goth teen helps break her free from a distorted spell. Her interest is piqued when he begs her to take him on the legendary Witches' Road.",
    poster_path: "https://image.tmdb.org/t/p/w500/v9Q673L7yX868953185672oM948.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/v9Q673L7yX868953185672oM948.jpg",
    trailer_key: "R9PTt_j3z2A",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "mcu", "agatha harkness", "witches road", "magic", "coven", "spooky", "comedy", "tv series"]
  },
  {
    id: 61889,
    title: "Daredevil",
    tagline: "Justice is blind.",
    year: 2015,
    release_date: "2015-04-10",
    vote_average: 8.3,
    vote_count: 6500,
    runtime: 1800,
    genres: ["Crime", "Drama", "Action & Adventure"],
    director: "Drew Goddard",
    cast: ["Charlie Cox", "Deborah Ann Woll", "Elden Henson", "Vincent D'Onofrio"],
    overview: "Blinded as a young boy, Matt Murdock fights injustice by day as a lawyer and by night as the superhero Daredevil in Hell's Kitchen, New York City.",
    poster_path: "https://image.tmdb.org/t/p/w500/QWbPaDxiB6LW2KiLG7RncvAYn.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/QWbPaDxiB6LW2KiLG7RncvAYn.jpg",
    trailer_key: "jAy6NJ_D5vU",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "daredevil", "matt murdock", "kingpin", "hells kitchen", "hallway fight", "gritty", "dark", "superhero masterpiece", "tv series"]
  },
  {
    id: 67178,
    title: "The Punisher",
    tagline: "The truth must be taken.",
    year: 2017,
    release_date: "2017-11-17",
    vote_average: 8.2,
    vote_count: 4800,
    runtime: 1300,
    genres: ["Crime", "Drama", "Action & Adventure"],
    director: "Steve Lightfoot",
    cast: ["Jon Bernthal", "Ebon Moss-Bachrach", "Ben Barnes", "Amber Rose Revah"],
    overview: "A former Marine out to punish the criminals responsible for his family's murder finds himself ensnared in a military conspiracy.",
    poster_path: "https://image.tmdb.org/t/p/w500/sF0Xq6676348873095034633L2.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/sF0Xq6676348873095034633L2.jpg",
    trailer_key: "OMW4A_V2Irs",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "punisher", "frank castle", "revenge", "military", "action", "gritty", "dark", "tv series"]
  },
  {
    id: 139164,
    title: "X-Men '97",
    tagline: "To me, my X-Men.",
    year: 2024,
    release_date: "2024-03-20",
    vote_average: 8.5,
    vote_count: 1800,
    runtime: 320,
    genres: ["Animation", "Action & Adventure", "Sci-Fi & Fantasy"],
    director: "Beau DeMayo, Jake Castorena",
    cast: ["Ray Chase", "Jennifer Hale", "Lenore Zann", "George Buza", "Matthew Waterson"],
    overview: "A band of mutants who use their uncanny gifts to protect a world that hates and fears them are challenged like never before, forced to face a dangerous and unexpected new future following the loss of Professor X.",
    poster_path: "https://image.tmdb.org/t/p/w500/9f38138761060938507204481.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w500/9f38138761060938507204481.jpg",
    trailer_key: "pv3Ss8o9Au4",
    country: "United States",
    media_type: "tv",
    keywords: ["marvel", "x-men", "x-men 97", "animation", "cyclops", "magneto", "wolverine", "nostalgic", "masterpiece", "tv series"]
  }
];

async function run() {
  console.log(`Starting Marvel Catalog Integration...`);
  let addedCount = 0;
  let updatedCount = 0;

  for (const item of marvelItems) {
    // 1. Verify / fix poster URL
    let poster = await verifyPoster(item.poster_path);
    if (!poster) {
      console.log(`Searching poster for: ${item.title}...`);
      poster = await searchTmdbPoster(item.title);
    }
    if (poster) {
      item.poster_path = poster;
      item.backdrop_path = poster;
    }

    const key = item.title.toLowerCase().trim();
    const existingIndex = movies.findIndex(m => m.title.toLowerCase().trim() === key);

    if (existingIndex === -1) {
      movies.push(item);
      existingTitles.add(key);
      addedCount++;
    } else {
      // Update with rich metadata if already present
      movies[existingIndex] = {
        ...movies[existingIndex],
        ...item
      };
      updatedCount++;
    }
  }

  // Save curatedMovies.json
  fs.writeFileSync(jsonPath, JSON.stringify(movies, null, 2), 'utf-8');
  console.log(`curatedMovies.json updated! Added: ${addedCount}, Updated: ${updatedCount}. Total catalog size: ${movies.length}`);

  // Save movies.csv
  const csvRows = [
    "title,genres,keywords,director,cast,year,vote_average,runtime,overview,country"
  ];

  for (const m of movies) {
    const t = `"${(m.title || '').replace(/"/g, '""')}"`;
    const g = `"${(m.genres || []).join(' ')}"`;
    const k = `"${(m.keywords || []).join(' ')}"`;
    const d = `"${(m.director || '').replace(/"/g, '""')}"`;
    const c = `"${(m.cast || []).join(' ').replace(/"/g, '""')}"`;
    const y = m.year || 2020;
    const v = m.vote_average || 7.5;
    const r = m.runtime || 120;
    const o = `"${(m.overview || '').replace(/"/g, '""')}"`;
    const country = m.country || 'USA';
    csvRows.push(`${t},${g},${k},${d},${c},${y},${v},${r},${o},${country}`);
  }

  fs.writeFileSync(csvPath, csvRows.join('\n'), 'utf-8');
  console.log(`movies.csv updated with all ${movies.length} titles!`);
}

run();
